"""Help command handler.

/help
"""

from __future__ import annotations


class HelpMixin:
    """Mixin providing /help command handler."""

    @staticmethod
    def _handle_help() -> str:
        return (
            "Available commands:\n"
            "  /config show              Show runtime configuration\n"
            "  /config interactive (/config i)  Interactive config editor\n"
            "  /config set <key> <value> Set a config value\n"
            "  /tools list               List all tools and status\n"
            "  /tools enable <name>      Enable a tool\n"
            "  /tools disable <name>     Disable a tool\n"
            "  /heads                    Show head states\n"
            "  /wake <head_id>           Load a model to GPU\n"
            "  /sleep <head_id>          Offload a model from GPU\n"
            "  /swap <head_id>           Switch active model\n"
            "  /brain [local|claude]     Show or switch brain mode\n"
            "  /model [name]             Show or switch Claude model (opus/sonnet/haiku)\n"
            "  /verbose                  Toggle verbose output (model, cost, turns)\n"
            "  /events                   Show recent events from watcher\n"
            "  /events clear             Clear event history\n"
            "  /events handle <N>        Route event N to brain for action\n"
            "  /status                   Full system status\n"
            "  /dashboard (/dash)        Observability dashboard with resource sparklines\n"
            "  /dashboard live [N]       Auto-refresh dashboard every N seconds (default 5)\n"
            "  /knowledge [query]        Search knowledge store\n"
            "  /session                  Current session info\n"
            "  /session export           Export transcript to markdown file\n"
            "  /session reset            Export + start fresh Claude conversation\n"
            "  /session capture [id]     Export SDK session JSONL + ingest claims\n"
            "  /session sdk-list         List recent SDK session files\n"
            "  /sessions                 List saved sessions\n"
            "  /mesh                     Show mesh peers\n"
            "  /pipeline                 Show pipeline status and config\n"
            "  /pipeline on|off          Enable/disable pipeline\n"
            "  /pipeline set <key> <val> Set pipeline config value\n"
            "  /services                 List background services\n"
            "  /services start <name>    Start a background service\n"
            "  /services stop <name>     Stop a running service\n"
            "  /services enable <name>   Enable auto-start for a service\n"
            "  /services disable <name>  Disable auto-start for a service\n"
            "  /spawn <command>          Start a background process\n"
            "  /ps                       List tracked processes\n"
            "  /output <pid> [lines]     Show process output\n"
            "  /kill <pid>               Kill a tracked process\n"
            "  /collab                   Review pending cross-session requests\n"
            "  /collab-respond <number>  Respond to a collaboration request\n"
            "  /collab-ignore <number>   Ignore a collaboration request\n"
            "  /responsive               Toggle responsive mode (auto-handle events)\n"
            "  /solve <task>             Autonomous solve: decompose → route → execute\n"
            "    [--marketplace]           Enable BotVibes marketplace delegation (Phase 3)\n"
            "  /route <task_types>       Find best head for task types (Phase 1)\n"
            "    [--privacy level]         Filter by data sensitivity (Phase 2)\n"
            "  /discover                 List discovered solvers (Phase 4)\n"
            "    [--type llm|vlm|...]      Filter by solver type\n"
            "    [--source huggingface|...]Filter by discovery source\n"
            "  /select <task_type>       Show solver preference (Phase 5)\n"
            "  /learn [task_type]        Show recipe learning status (Phase 6)\n"
            "  /resolve <claim_id>       Mark a claim as resolved (stops resurfacing)\n"
            "  /harvest                  Session harvester status\n"
            "  /harvest run              Harvest MEMORY.md/CLAUDE.md from all Claude projects\n"
            "  /harvest list             List discovered projects\n"
            "  /help                     Show this help\n"
            "  exit / quit / q           Exit\n"
            "\n"
            "Multi-line input:\n"
            "  line ending with \\        Backslash continuation (next line appended)\n"
            "  ```                       Start block mode — type ``` again to submit"
        )
